version: '3.9'

services:
  grafana-db:
    image: postgres:17
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - grafana-db-data:/var/lib/postgresql/data
    networks:
      - grafana-net

  grafana:
    image: grafana/grafana:latest
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`grafana.seudominio.com`)"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.tls.certresolver=myresolver"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: grafana-db
      GF_DATABASE_NAME: ${POSTGRES_DATABASE}
      GF_DATABASE_USER: ${POSTGRES_DB_USER}
      GF_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ../grafana.ini:/etc/grafana/grafana.ini
      - ../ldap.toml:/etc/grafana/ldap.toml
    depends_on:
      - grafana-db
    networks:
      - grafana-net
      - traefik-net

volumes:
  postgres_data:
  grafana-db-data:
  grafana-data:

networks:
  grafana-net:
    driver: overlay
    external: true
  traefik-net:
    driver: overlay
    external: true
